name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
          
      - name: Sphinx build
        run: | 
          cd docs/source/
          make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/source/build/html/
          force_orphan: true

# # This is a basic workflow to help you get started with Actions

# name: Build-sphinx-docs
# # Controls when the workflow will run

# permissions:
#   id-token: write
#   contents: write
#   actions: write
#   checks: write
#   deployments: write
#   discussions: write
#   issues: write
#   pages: read
#   packages: write
#   pull-requests: write
#   repository-projects: write
#   security-events: write
#   statuses: write
  
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs: 
#   # This workflow contains a single job called "build"
#   build: 
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       - name: Set up Python 3.10
#         uses: actions/setup-python@v2
#         with:
#            python-version: "3.10"
#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!
        
#       - name: Install dependencies
#         run: | 
#           python -m pip install --upgrade pip
#           pip install -r docs/requirements.txt
#       - name: Build HTML
#         run: | 
#           cd docs/source/
#           make html
#       - name: Run ghp-import
#         run: | 
#           ghp-import -n -p -f docs/source/build/html

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
